In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#manually type the dataset as a dectionary
data ={
    'student-ID':[1001, 1002, 1003, 1004, 1005, 1001, 1006, 1007, 1008, 1009],
    'county': ['Nakuru', 'Narok', 'Nakuru', 'Narok', 'Kakamega', 'Nakuru', 'Nairobi', None, 'Narok', 'Nakuru'],
    'Study_Hours_Per_Week': [15, 8, 20, None, 12, 15, 30, 10, 25, 18],
    'Attendance_Percent':[85, 60, 92, 55, 78, 85, 95, 65, 88, None], 
    'Fee_Balance_Ksh':[0, 15000, 0, 25000, 5000, 0, 0, 18000, 2000, 12000],
    'Prvious_Grade':[72, 48, 85, 45, 65, 72, 90, 50, 82, 58],
    'Student_TYpe':['Regular', 'Regular', 'Scholarship', 'Regular', 'Scholarship', 'Regular', 'Regular', 'Scholarship', 'Regular', 'Regular'],
    'Academic_Risk':[0, 1, 0, 1, 0, 0, 0, 1, 0, 1]
}
#Converts the dataset dictionary into panda Data Frame

df= pd.DataFrame(data)


#to diplay all the rows and columns of the Panda Dataframe with trancation(cutting)
pd.set_option('display.max_row', None)
pd.set_option('display.max_columns', None)
#to display the dataframe
df

,student-ID,county,Study_Hours_Per_Week,Attendance_Percent,Fee_Balance_Ksh,Prvious_Grade,Student_TYpe,Academic_Risk
0,1001,Nakuru,15.0,85.0,0,72,Regular,0
1,1002,Narok,8.0,60.0,15000,48,Regular,1
2,1003,Nakuru,20.0,92.0,0,85,Scholarship,0
3,1004,Narok,NaN,55.0,25000,45,Regular,1
4,1005,Kakamega,12.0,78.0,5000,65,Scholarship,0
5,1001,Nakuru,15.0,85.0,0,72,Regular,0
6,1006,Nairobi,30.0,95.0,0,90,Regular,0
7,1007,NaN,10.0,65.0,18000,50,Scholarship,1
8,1008,Narok,25.0,88.0,2000,82,Regular,0
9,1009,Nakuru,18.0,NaN,12000,58,Reguylar,1

In [3]:
#----- DATA CLEANING -----
#to handel duplicate valuse
df=df.drop_duplicates()

#To handel th missing vales 

#missing valuse in county
df['county']=df['county'].fillna(df['county'].mode()[0])

#missing valuse in study hours per week
df['Study_Hours_Per_Week']=df['Study_Hours_Per_Week'].fillna(df['Study_Hours_Per_Week'].median())

#missing valuse in Attendances perrcent
df['Attendance_Percent']=df['Attendance_Percent'].fillna(df['Attendance_Percent'].median())

#Missing valuse in fee balance
df['Fee_Balance_Ksh']=df['Fee_Balance_Ksh'].fillna(df['Fee_Balance_Ksh'].median())

#MIssing valuse in privious grade
df['Prvious_Grade']=df['Prvious_Grade'].fillna(df['Prvious_Grade'].median())

#Missing valuse instudent type
df['Student_TYpe']=df['Student_TYpe'].fillna(df['Student_TYpe'].mode()[0])

#Missing valuse in accademic Risk
df['Academic_Risk']=df['Academic_Risk'].fillna(df['Academic_Risk'].mode()[0])

#check for missing values
df.isnull().sum()

df

#---- Resons for uing median an mode -----
#median is used in Numerical fields becouse it is resistant to outliers
#mode is used in categorical fields becouse it can not be averaged or found with a median

,student-ID,county,Study_Hours_Per_Week,Attendance_Percent,Fee_Balance_Ksh,Prvious_Grade,Student_TYpe,Academic_Risk
0,1001,Nakuru,15.0,85.0,0,72,Regular,0
1,1002,Narok,8.0,60.0,15000,48,Regular,1
2,1003,Nakuru,20.0,92.0,0,85,Scholarship,0
3,1004,Narok,16.5,55.0,25000,45,Regular,1
4,1005,Kakamega,12.0,78.0,5000,65,Scholarship,0
6,1006,Nairobi,30.0,95.0,0,90,Regular,0
7,1007,Nakuru,10.0,65.0,18000,50,Scholarship,1
8,1008,Narok,25.0,88.0,2000,82,Regular,0
9,1009,Nakuru,18.0,81.5,12000,58,Reguylar,1